function cmap = customize_colormap(v_top, v_bot,v_mid, c_top, c_bot, c_mid)
    if nargin < 6; c_mid = ones(1,3); end
    if nargin < 4; c_top = [215,120,50]./255; c_bot = [97, 33, 141]./255; end
    
    %case 1: v_mid is below v_bot
    if v_mid < v_bot
        diff_lb = v_bot - v_mid; diff_ub = v_top - v_bot;
        c_steps = round(100/(1 + diff_ub/diff_lb));
        cmap_temp = [linspace(c_top(1),c_mid(1),100)',...
            linspace(c_top(2),c_mid(2),100)',...
            linspace(c_top(3),c_mid(3),100)'];
        cmap_bot_new = cmap_temp(100-c_steps+1,:);
        cmap = [linspace(cmap_bot_new(1),c_top(1), 100)',...
            linspace(cmap_bot_new(2), c_top(2), 100)',...
            linspace(cmap_bot_new(3), c_top(3), 100)'];
    %case 2: v_mid is above v_top
    elseif v_mid > v_top
        diff_lb = v_top - v_bot; diff_ub = v_mid - v_top;
        c_steps = round(100/(1 + diff_lb/diff_ub));
        cmap_temp = [linspace(c_mid(1),c_bot(1),100)',...
            linspace(c_mid(2),c_bot(2),100)',...
            linspace(c_mid(3),c_bot(3),100)'];
        cmap_top_new = cmap_temp(c_steps,:);
        cmap = [linspace(c_bot(1), cmap_top_new(1), 100)',...
            linspace(c_bot(2), cmap_top_new(2), 100)',...
            linspace(c_bot(3), cmap_top_new(3), 100)'];
    %case 3: v_mid is actually in between v_top and v_bot
    else
        diff_lb = v_mid - v_bot; diff_ub = v_top - v_mid;
        if diff_ub > diff_lb 
            c_steps = round(diff_lb/diff_ub*100);
            cmap_temp = [linspace(c_mid(1),c_bot(1),100)',...
                linspace(c_mid(2),c_bot(2),100)',...
                linspace(c_mid(3),c_bot(3),100)'];
            cmap1 = [linspace(c_top(1), c_mid(1), 100)',...
                linspace(c_top(2), c_mid(2), 100)',...
                linspace(c_top(3), c_mid(3), 100)'];
            cmap2 = cmap_temp(1:c_steps,:);
            cmap = [flipud(cmap2); flipud(cmap1)];
        else
            c_steps = round(diff_ub/diff_lb*100);
            cmap_temp = [linspace(c_top(1),c_mid(1),100)',...
                linspace(c_top(2),c_mid(2),100)',...
                linspace(c_top(3),c_mid(3),100)'];
            cmap1 = [linspace(c_mid(1), c_bot(1), 100)',...
                linspace(c_mid(2), c_bot(2), 100)',...
                linspace(c_mid(3), c_bot(3), 100)'];
            cmap2 = cmap_temp((100-c_steps+1):end,:);
            cmap = [flipud(cmap1); flipud(cmap2)];
        end
    end     
end